### ISSUE TITLE
Pin alignment for Pi Pico are off by one

### ISSUE THREAD

**Issue by swb1701** [adafruit/Adafruit-AR#11]

**Comment by ladyada** [comment]
please provide some information on what you're reffering to

**Comment by swb1701** [comment]
![adafruit-ar-screenshot](https://user-images.githubusercontent.com/5921574/107859896-87159900-6e0a-11eb-8d93-0814ccb1456c.png)

**Comment by swb1701** [comment]
In all orientations the Pi Pico pins didn't align.

**Comment by TrevKnows** [comment]
Hi, What device are you using?

**Comment by dhalbert** [comment]
I see this issue on an iPhone 6S running iOS 14.4 and an iPad 6th gen running iPadOS 14.5 beta latest.

**Comment by swb1701** [comment]
It failed for me on an iPhone 8 running 14.4

**Comment by TrevKnows** [comment]
Gotcha. What version are you running of Adafruit AR? The version number is on the main screen.

**Comment by swb1701** [comment]
v.1.10.4

**Comment by dhalbert** [comment]
Same for me; there's no newer update in the App Store.

**Comment by TrevKnows** [comment]
Thanks y'all. Im working on this issue. It works fine on 3 different iPhones I have, but I was able to replicate the problem on my iPad. Either way, I'll find a fix!

**Comment by TrevKnows** [comment]
Howdy! There is a new update for Adafruit AR that fixes the pin alignment overlay issue for the Raspberry Pi Pico.

**Comment by dhalbert** [comment]
This works for me on the iPHone 6s and the iPad. Thanks!

**Comment by TrevKnows** [comment]
Awesome!
